---
### deploy node
#- name: install one specific version of ansible
#  yum: name=ansible-{{ansible_version_min}} state=present

#- name: install the latest version of git
#  yum: name=git state=latest
  
#- name: install the latest version of python-devel
#  yum: name=python-devel state=latest
  
#- name: install the latest version of libffi-devel
#  yum: name=libffi-devel state=latest
  
#- name: install the latest version of openssl-devel
#  yum: name=openssl-devel state=latest
  
#- name: install the latest version of gcc
#  yum: name=gcc state=latest
  
#- name: install the latest version of python-openstackclient
#  yum: name=python-openstackclient state=latest
  
#- name: install the latest version of python-neutronclient
#  yum: name=python-neutronclient state=latest

### all node
- name: install the latest version of epel-release
  yum: name=epel-release state=latest
  
- name: install the latest version of python-pip
  yum: name=python-pip state=latest
  
- name: install the latest version of docker
  yum: name=docker state=latest
  
- name: install the latest version of docker-py
  command: pip install -U docker-py 
  
- name: install the latest version of ntp and start service
  yum: name=ntp state=latest